Use strtoul instead of atol for ScanCache.
clamfs.cxx:1373:56: error: implicit conversion changes signedness: 'long'
to 'unsigned long' [-Werror,-Wsign-conversion]
        cache = new ScanCache(atol(config["entries"]), atol(config["expire"]));
                    ~~~~~~~~~                          ^~~~~~~~~~~~~~~~~~~~~~
clamfs.cxx:1373:31: error: implicit conversion changes signedness: 'long'
to 'unsigned long' [-Werror,-Wsign-conversion]
        cache = new ScanCache(atol(config["entries"]), atol(config["expire"]));
                    ~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~